### YamlMime:ManagedReference
items:
- uid: System.Security.Authentication.AuthenticationException
  id: AuthenticationException
  children:
  - System.Security.Authentication.AuthenticationException.#ctor
  - System.Security.Authentication.AuthenticationException.#ctor(System.String)
  - System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AuthenticationException
  nameWithType: AuthenticationException
  fullName: System.Security.Authentication.AuthenticationException
  type: Class
  summary: "A kivétel fordul elő, ha a hitelesítés nem sikerül egy hitelesítési adatfolyamhoz."
  remarks: "A <xref:System.Net.Security.NegotiateStream>és <xref:System.Net.Security.SslStream>osztályok throw ezt a kivételt, amikor az ügyfél vagy kiszolgáló nem lehet hitelesíteni.</xref:System.Net.Security.SslStream> </xref:System.Net.Security.NegotiateStream> Ez a kivétel történt, amikor újra a hitelesítési más hitelesítő adatokkal. Ha a hitelesítés nem lehet újrapróbálkozni egy <xref:System.Security.Authentication.InvalidCredentialException>helyett a AuthenticationException történt.</xref:System.Security.Authentication.InvalidCredentialException>"
  example:
  - <xref:System.Net.Security.NegotiateStream> &#124; <xref:System.Net.Security.SslStream>
  syntax:
    content: 'public class AuthenticationException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Security.Authentication.AuthenticationException.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  name: AuthenticationException()
  nameWithType: AuthenticationException.AuthenticationException()
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Security.Authentication.AuthenticationException&quot;> </xref> osztály nem üzenettel."
  remarks: "Ez a konstruktor nincs semmi hatása."
  syntax:
    content: public AuthenticationException ();
    parameters: []
  overload: System.Security.Authentication.AuthenticationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  name: AuthenticationException(String)
  nameWithType: AuthenticationException.AuthenticationException(String)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Security.Authentication.AuthenticationException&quot;> </xref> a megadott üzenet osztályra."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonságot, amelyben a szöveget a `message` paraméter.</xref:System.Exception.Message%2A> A <xref:System.Exception.InnerException%2A>tulajdonsága `null`.</xref:System.Exception.InnerException%2A>"
  syntax:
    content: public AuthenticationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>, amely leírja, hogy a hitelesítés sikertelen.</xref:System.String>"
  overload: System.Security.Authentication.AuthenticationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  name: AuthenticationException(SerializationInfo,StreamingContext)
  nameWithType: AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Security.Authentication.AuthenticationException&quot;> </xref> osztály adott példányait a <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> és <xref:System.Runtime.Serialization.StreamingContext>osztályok.</xref:System.Runtime.Serialization.StreamingContext>"
  syntax:
    content: protected AuthenticationException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> az új deszerializálásához szükséges adatokat tartalmazó példány <xref href=&quot;System.Security.Authentication.AuthenticationException&quot;> </xref> példány."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>példány.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Security.Authentication.AuthenticationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Security.Authentication.AuthenticationException
  langs:
  - csharp
  name: AuthenticationException(String,Exception)
  nameWithType: AuthenticationException.AuthenticationException(String,Exception)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Security.Authentication.AuthenticationException&quot;> </xref> osztály a megadott üzenet és a belső kivételben találhatók."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonságot, amelyben a szöveget a `message` paraméter és inicializálása a <xref:System.Exception.InnerException%2A>tulajdonság a `innerException` paraméter értéke.</xref:System.Exception.InnerException%2A> </xref:System.Exception.Message%2A>"
  syntax:
    content: public AuthenticationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>, amely leírja, hogy a hitelesítés sikertelen.</xref:System.String>"
    - id: innerException
      type: System.Exception
      description: "A <xref:System.Exception>, amely a jelenlegi kivétel okát.</xref:System.Exception>"
  overload: System.Security.Authentication.AuthenticationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Security.Authentication.AuthenticationException.#ctor
  parent: System.Security.Authentication.AuthenticationException
  isExternal: false
  name: AuthenticationException()
  nameWithType: AuthenticationException.AuthenticationException()
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException()
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String)
  parent: System.Security.Authentication.AuthenticationException
  isExternal: false
  name: AuthenticationException(String)
  nameWithType: AuthenticationException.AuthenticationException(String)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Security.Authentication.AuthenticationException
  isExternal: false
  name: AuthenticationException(SerializationInfo,StreamingContext)
  nameWithType: AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Security.Authentication.AuthenticationException.#ctor(System.String,System.Exception)
  parent: System.Security.Authentication.AuthenticationException
  isExternal: false
  name: AuthenticationException(String,Exception)
  nameWithType: AuthenticationException.AuthenticationException(String,Exception)
  fullName: System.Security.Authentication.AuthenticationException.AuthenticationException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Security.Authentication.AuthenticationException.#ctor*
  parent: System.Security.Authentication.AuthenticationException
  isExternal: false
  name: AuthenticationException
  nameWithType: AuthenticationException.AuthenticationException
