### YamlMime:ManagedReference
items:
- uid: System.IO.PipeException
  id: PipeException
  children:
  - System.IO.PipeException.#ctor
  - System.IO.PipeException.#ctor(System.String)
  - System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IO.PipeException.#ctor(System.String,System.Exception)
  - System.IO.PipeException.#ctor(System.String,System.Int32)
  - System.IO.PipeException.ErrorCode
  langs:
  - csharp
  name: PipeException
  nameWithType: PipeException
  fullName: System.IO.PipeException
  type: Class
  summary: "Ha hiba történik egy nevesített csövet belül kiváltva."
  syntax:
    content: 'public class PipeException : System.IO.IOException'
  inheritance:
  - System.IO.IOException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IO.PipeException.#ctor
  id: '#ctor'
  parent: System.IO.PipeException
  langs:
  - csharp
  name: PipeException()
  nameWithType: PipeException.PipeException()
  fullName: System.IO.PipeException.PipeException()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IO.PipeException&quot;> </xref> osztály."
  syntax:
    content: public PipeException ();
    parameters: []
  overload: System.IO.PipeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.PipeException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.PipeException
  langs:
  - csharp
  name: PipeException(String)
  nameWithType: PipeException.PipeException(String)
  fullName: System.IO.PipeException.PipeException(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IO.PipeException&quot;> </xref> osztály egy adott hiba miatt."
  syntax:
    content: public PipeException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel okát tartalmazó karakterlánc."
  overload: System.IO.PipeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IO.PipeException
  langs:
  - csharp
  name: PipeException(SerializationInfo,StreamingContext)
  nameWithType: PipeException.PipeException(SerializationInfo,StreamingContext)
  fullName: System.IO.PipeException.PipeException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IO.PipeException&quot;> </xref> a megadott szerializálási adat és adatfolyam-kontextus osztály."
  syntax:
    content: protected PipeException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> tartalmazó szerializálni a kivételt szükséges összes adatot."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>, amely megadja, hogy a forrás- és az adatfolyam.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IO.PipeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.PipeException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.PipeException
  langs:
  - csharp
  name: PipeException(String,Exception)
  nameWithType: PipeException.PipeException(String,Exception)
  fullName: System.IO.PipeException.PipeException(String,Exception)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IO.PipeException&quot;> </xref> osztály a megadott hibaüzenet és a belső kivételben találhatók."
  syntax:
    content: public PipeException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel okát tartalmazó karakterlánc."
    - id: inner
      type: System.Exception
      description: "A <xref:System.Exception>, hogy jelezni, hogy az adott kivételt okozott.</xref:System.Exception>"
  overload: System.IO.PipeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.PipeException.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.IO.PipeException
  langs:
  - csharp
  name: PipeException(String,Int32)
  nameWithType: PipeException.PipeException(String,Int32)
  fullName: System.IO.PipeException.PipeException(String,Int32)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IO.PipeException&quot;> </xref> osztály egy megadott hibaüzenet és a hibakód."
  syntax:
    content: public PipeException (string message, int errorCode);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel okát tartalmazó karakterlánc."
    - id: errorCode
      type: System.Int32
      description: "Egész szám, amely tartalmazza a hibakódot."
  overload: System.IO.PipeException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.PipeException.ErrorCode
  id: ErrorCode
  parent: System.IO.PipeException
  langs:
  - csharp
  name: ErrorCode
  nameWithType: PipeException.ErrorCode
  fullName: System.IO.PipeException.ErrorCode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.IO
  summary: "Lekérdezi a hibakód a következő kivétellel vissza kell adni."
  syntax:
    content: public virtual int ErrorCode { get; }
    return:
      type: System.Int32
      description: "Egész szám a következő hibakóddal azzal a kivétellel vissza kell adni."
  overload: System.IO.PipeException.ErrorCode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IO.IOException
  isExternal: false
  name: System.IO.IOException
- uid: System.IO.PipeException.#ctor
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException()
  nameWithType: PipeException.PipeException()
  fullName: System.IO.PipeException.PipeException()
- uid: System.IO.PipeException.#ctor(System.String)
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException(String)
  nameWithType: PipeException.PipeException(String)
  fullName: System.IO.PipeException.PipeException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException(SerializationInfo,StreamingContext)
  nameWithType: PipeException.PipeException(SerializationInfo,StreamingContext)
  fullName: System.IO.PipeException.PipeException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IO.PipeException.#ctor(System.String,System.Exception)
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException(String,Exception)
  nameWithType: PipeException.PipeException(String,Exception)
  fullName: System.IO.PipeException.PipeException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.IO.PipeException.#ctor(System.String,System.Int32)
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException(String,Int32)
  nameWithType: PipeException.PipeException(String,Int32)
  fullName: System.IO.PipeException.PipeException(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.IO.PipeException.ErrorCode
  parent: System.IO.PipeException
  isExternal: false
  name: ErrorCode
  nameWithType: PipeException.ErrorCode
  fullName: System.IO.PipeException.ErrorCode
- uid: System.IO.PipeException.#ctor*
  parent: System.IO.PipeException
  isExternal: false
  name: PipeException
  nameWithType: PipeException.PipeException
- uid: System.IO.PipeException.ErrorCode*
  parent: System.IO.PipeException
  isExternal: false
  name: ErrorCode
  nameWithType: PipeException.ErrorCode
