### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.RequestException
  id: RequestException
  children:
  - System.IdentityModel.RequestException.#ctor
  - System.IdentityModel.RequestException.#ctor(System.String)
  - System.IdentityModel.RequestException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.RequestException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RequestException
  nameWithType: RequestException
  fullName: System.IdentityModel.RequestException
  type: Class
  summary: "A kérelem sikertelen végrehajtása esetén kivételek alaposztálya."
  syntax:
    content: 'public abstract class RequestException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.RequestException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.RequestException
  langs:
  - csharp
  name: RequestException()
  nameWithType: RequestException.RequestException()
  fullName: System.IdentityModel.RequestException.RequestException()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.RequestException&quot;> </xref> osztály."
  remarks: "Ez a konstruktor inicializálja a <xref:SystemException.Message>tulajdonság egy rendszer által megadott üzenetet, amely leírja a hibát az új példányának.</xref:SystemException.Message> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       A következő táblázat az új példány kezdeti tulajdonságértéket.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: protected RequestException ();
    parameters: []
  overload: System.IdentityModel.RequestException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.RequestException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.RequestException
  langs:
  - csharp
  name: RequestException(String)
  nameWithType: RequestException.RequestException(String)
  fullName: System.IdentityModel.RequestException.RequestException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.RequestException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message>tulajdonság új kivétel használva a `message` paraméter.</xref:System.Exception.Message> A tartalma `message` célja, hogy ember által is értelmezhető. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított.       A következő táblázat az új példány kezdeti tulajdonságértéket.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: protected RequestException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
  overload: System.IdentityModel.RequestException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.RequestException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.RequestException
  langs:
  - csharp
  name: RequestException(SerializationInfo,StreamingContext)
  nameWithType: RequestException.RequestException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.RequestException.RequestException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.RequestException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: protected RequestException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> objektum, amely a szerializált objektum adatokat tartalmaz."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>objektum, amely a cél- és környezeti információkat tartalmaz.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.RequestException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.RequestException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.RequestException
  langs:
  - csharp
  name: RequestException(String,Exception)
  nameWithType: RequestException.RequestException(String,Exception)
  fullName: System.IdentityModel.RequestException.RequestException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.RequestException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException>tulajdonság.</xref:System.Exception.InnerException> A <xref:System.Exception.InnerException>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza.</xref:System.Exception.InnerException>       A következő táblázat az új példány kezdeti tulajdonságértéket.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException>| A belső kivétel referencia. |}   | <xref:System.Exception.Message>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: protected RequestException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: innerException
      type: System.Exception
      description: "A <xref:System.Exception>, amely a jelenlegi kivétel okát.</xref:System.Exception> Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.IdentityModel.RequestException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.RequestException.#ctor
  parent: System.IdentityModel.RequestException
  isExternal: false
  name: RequestException()
  nameWithType: RequestException.RequestException()
  fullName: System.IdentityModel.RequestException.RequestException()
- uid: System.IdentityModel.RequestException.#ctor(System.String)
  parent: System.IdentityModel.RequestException
  isExternal: false
  name: RequestException(String)
  nameWithType: RequestException.RequestException(String)
  fullName: System.IdentityModel.RequestException.RequestException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.RequestException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.RequestException
  isExternal: false
  name: RequestException(SerializationInfo,StreamingContext)
  nameWithType: RequestException.RequestException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.RequestException.RequestException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.RequestException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.RequestException
  isExternal: false
  name: RequestException(String,Exception)
  nameWithType: RequestException.RequestException(String,Exception)
  fullName: System.IdentityModel.RequestException.RequestException(String,Exception)
- uid: System.IdentityModel.RequestException.#ctor*
  parent: System.IdentityModel.RequestException
  isExternal: false
  name: RequestException
  nameWithType: RequestException.RequestException
