### YamlMime:ManagedReference
items:
- uid: System.Runtime.InteropServices.ExternalException
  id: ExternalException
  children:
  - System.Runtime.InteropServices.ExternalException.#ctor
  - System.Runtime.InteropServices.ExternalException.#ctor(System.String)
  - System.Runtime.InteropServices.ExternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Exception)
  - System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Int32)
  - System.Runtime.InteropServices.ExternalException.ErrorCode
  - System.Runtime.InteropServices.ExternalException.ToString
  langs:
  - csharp
  name: ExternalException
  nameWithType: ExternalException
  fullName: System.Runtime.InteropServices.ExternalException
  type: Class
  summary: "Az összes COM-együttműködési kivételeket és strukturált kivételkezelő (SEH) kivételek alap kivétel típusa."
  remarks: "A hagyományos és a közös nyelvi futtatókörnyezet közötti együttműködés javítása érdekében a <xref:System.Runtime.InteropServices.ExternalException.ErrorCode%2A>a tulajdonság tárolja az egész szám (HRESULT), amely meghatározza a hibát.</xref:System.Runtime.InteropServices.ExternalException.ErrorCode%2A> Felhasználó által definiált kivételek soha nem kell származnia `ExternalException`, és egy `ExternalException` soha nem kell a felhasználói kód által okozott. Használja az adott kivételeket, amelyek a `ExternalException` helyette.       `ExternalException`használja a HRESULT E_FAIL, amely 0x80004005 értékkel rendelkezik.       `ExternalException`az alapértelmezett értéket használja, <xref:System.Object.Equals%2A>megvalósítása, amely támogatja a hivatkozási egyenlőség.</xref:System.Object.Equals%2A>       Példányának kezdeti értékeinek listája `ExternalException`, tekintse meg a `ExternalException` konstruktor."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ExternalException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ExternalException()
  nameWithType: ExternalException.ExternalException()
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Egy új példányát inicializálja a <xref uid=&quot;langword_csharp_ExternalException&quot; name=&quot;ExternalException&quot; href=&quot;&quot;> </xref> osztály alapértelmezett tulajdonságokkal."
  remarks: "Az alábbi táblázat a kezdeti példányának tulajdonságértékek `ExternalException`.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| Egy üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExternalException ();
    parameters: []
  overload: System.Runtime.InteropServices.ExternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ExternalException(String)
  nameWithType: ExternalException.ExternalException(String)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Egy új példányát inicializálja a <xref uid=&quot;langword_csharp_ExternalException&quot; name=&quot;ExternalException&quot; href=&quot;&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Az alábbi táblázat a kezdeti példányának tulajdonságértékek `ExternalException`.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExternalException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely meghatározza a kivétel az az oka."
  overload: System.Runtime.InteropServices.ExternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ExternalException(SerializationInfo,StreamingContext)
  nameWithType: ExternalException.ExternalException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Egy új példányát inicializálja a <xref uid=&quot;langword_csharp_ExternalException&quot; name=&quot;ExternalException&quot; href=&quot;&quot;> </xref> osztály szerializációs adatokból."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben. További információkért lásd: [XML és a SOAP-szerializálási](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected ExternalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Runtime.InteropServices.ExternalException.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>info</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ExternalException(String,Exception)
  nameWithType: ExternalException.ExternalException(String,Exception)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.InteropServices.ExternalException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy `null` Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Runtime.InteropServices.ExternalException>.</xref:System.Runtime.InteropServices.ExternalException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExternalException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: inner
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `inner` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Runtime.InteropServices.ExternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ExternalException(String,Int32)
  nameWithType: ExternalException.ExternalException(String,Int32)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String,Int32)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Egy új példányát inicializálja a <xref uid=&quot;langword_csharp_ExternalException&quot; name=&quot;ExternalException&quot; href=&quot;&quot;> </xref> a megadott hibaüzenet és a hiba a HRESULT osztályt."
  remarks: "Az alábbi táblázat a kezdeti példányának tulajdonságértékek `ExternalException`.      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Runtime.InteropServices.ExternalException.ErrorCode%2A>| A hiba a HRESULT. |}   | <xref:System.Exception.InnerException%2A>| Egy null hivatkozás (`Nothing` a Visual Basic nyelvben). |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.InteropServices.ExternalException.ErrorCode%2A>"
  syntax:
    content: public ExternalException (string message, int errorCode);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely meghatározza a kivétel az az oka."
    - id: errorCode
      type: System.Int32
      description: "A hiba a HRESULT."
  overload: System.Runtime.InteropServices.ExternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.ErrorCode
  id: ErrorCode
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ErrorCode
  nameWithType: ExternalException.ErrorCode
  fullName: System.Runtime.InteropServices.ExternalException.ErrorCode
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "Lekérdezi a <xref uid=&quot;langword_csharp_HRESULT&quot; name=&quot;HRESULT&quot; href=&quot;&quot;> </xref> tartalmazza a hiba."
  remarks: "Lásd: [közös HRESULT értékek](https://msdn.microsoft.com/library/windows/desktop/aa378137.aspx) minél több listája gyakran észlelt, miközben hibakódok. `HRESULT`a Winerror.h fejlécfájlt értékek vannak definiálva."
  syntax:
    content: public virtual int ErrorCode { get; }
    return:
      type: System.Int32
      description: "A <xref uid=&quot;langword_csharp_HRESULT&quot; name=&quot;HRESULT&quot; href=&quot;&quot;> </xref> tartalmazza a hiba."
  overload: System.Runtime.InteropServices.ExternalException.ErrorCode*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.InteropServices.ExternalException.ToString
  id: ToString
  parent: System.Runtime.InteropServices.ExternalException
  langs:
  - csharp
  name: ToString()
  nameWithType: ExternalException.ToString()
  fullName: System.Runtime.InteropServices.ExternalException.ToString()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  summary: "A hiba a HRESULT tartalmazó karakterláncot ad vissza."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "A HRESULT jelölő karakterlánccá."
  overload: System.Runtime.InteropServices.ExternalException.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Runtime.InteropServices.ExternalException.#ctor
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException()
  nameWithType: ExternalException.ExternalException()
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException()
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String)
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException(String)
  nameWithType: ExternalException.ExternalException(String)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException(SerializationInfo,StreamingContext)
  nameWithType: ExternalException.ExternalException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Exception)
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException(String,Exception)
  nameWithType: ExternalException.ExternalException(String,Exception)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.InteropServices.ExternalException.#ctor(System.String,System.Int32)
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException(String,Int32)
  nameWithType: ExternalException.ExternalException(String,Int32)
  fullName: System.Runtime.InteropServices.ExternalException.ExternalException(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Runtime.InteropServices.ExternalException.ErrorCode
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ErrorCode
  nameWithType: ExternalException.ErrorCode
  fullName: System.Runtime.InteropServices.ExternalException.ErrorCode
- uid: System.Runtime.InteropServices.ExternalException.ToString
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ToString()
  nameWithType: ExternalException.ToString()
  fullName: System.Runtime.InteropServices.ExternalException.ToString()
- uid: System.Runtime.InteropServices.ExternalException.#ctor*
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ExternalException
  nameWithType: ExternalException.ExternalException
- uid: System.Runtime.InteropServices.ExternalException.ErrorCode*
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ErrorCode
  nameWithType: ExternalException.ErrorCode
- uid: System.Runtime.InteropServices.ExternalException.ToString*
  parent: System.Runtime.InteropServices.ExternalException
  isExternal: false
  name: ToString
  nameWithType: ExternalException.ToString
