### YamlMime:ManagedReference
items:
- uid: System.ContextMarshalException
  id: ContextMarshalException
  children:
  - System.ContextMarshalException.#ctor
  - System.ContextMarshalException.#ctor(System.String)
  - System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ContextMarshalException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ContextMarshalException
  nameWithType: ContextMarshalException
  fullName: System.ContextMarshalException
  type: Class
  summary: "A kivétel fordul elő, amikor sikertelen kísérlet történt objektum végrehajtásra való környezeti határon keresztül."
  remarks: "Objektumok érték vagy hivatkozással is átadásra. Olyan típusú, amely nem készíthető elő átadásra környezeti határon keresztül továbbítja tett bármilyen kísérlet a ContextMarshalException eredményez.       ContextMarshalException a HRESULT COR_E_CONTEXTMARSHAL, amelynek az értéke 0x80131504L használja.       Az alapértelmezett értéket használja, ContextMarshalException <xref:System.Object.Equals%2A>megvalósítása, amely támogatja a hivatkozási egyenlőség.</xref:System.Object.Equals%2A>       A kezdeti tulajdonságértékek ContextMarshalException példányt listájáért lásd: a <xref:System.ContextMarshalException.%23ctor%2A>konstruktorok.</xref:System.ContextMarshalException.%23ctor%2A>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ContextMarshalException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ContextMarshalException.#ctor
  id: '#ctor'
  parent: System.ContextMarshalException
  langs:
  - csharp
  name: ContextMarshalException()
  nameWithType: ContextMarshalException.ContextMarshalException()
  fullName: System.ContextMarshalException.ContextMarshalException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ContextMarshalException&quot;> </xref> osztály alapértelmezett tulajdonságokkal."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ContextMarshalException>.</xref:System.ContextMarshalException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Az üres karakterlánc (&quot;&quot;). |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ContextMarshalException ();
    parameters: []
  overload: System.ContextMarshalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ContextMarshalException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ContextMarshalException
  langs:
  - csharp
  name: ContextMarshalException(String)
  nameWithType: ContextMarshalException.ContextMarshalException(String)
  fullName: System.ContextMarshalException.ContextMarshalException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ContextMarshalException&quot;> </xref> osztály egy adott hiba miatt."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ContextMarshalException>.</xref:System.ContextMarshalException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ContextMarshalException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
  overload: System.ContextMarshalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.ContextMarshalException
  langs:
  - csharp
  name: ContextMarshalException(SerializationInfo,StreamingContext)
  nameWithType: ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)
  fullName: System.ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ContextMarshalException&quot;> </xref> a szerializált adatok osztályt."
  syntax:
    content: protected ContextMarshalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> , amely tartalmazza a kivétel lépett fel az éppen szerializált objektum adatait."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>, amely a cél- és környezeti információkat tartalmaz.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.ContextMarshalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ContextMarshalException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ContextMarshalException
  langs:
  - csharp
  name: ContextMarshalException(String,Exception)
  nameWithType: ContextMarshalException.ContextMarshalException(String,Exception)
  fullName: System.ContextMarshalException.ContextMarshalException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ContextMarshalException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy `null` Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.ContextMarshalException>.</xref:System.ContextMarshalException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A belső kivétel referencia. |}   | <xref:System.Exception.Message%2A>| A üzenetet hiba karakterlánca. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ContextMarshalException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A hibaüzenet, amely ismerteti a kivétel az az oka."
    - id: inner
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `inner` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.ContextMarshalException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ContextMarshalException.#ctor
  parent: System.ContextMarshalException
  isExternal: false
  name: ContextMarshalException()
  nameWithType: ContextMarshalException.ContextMarshalException()
  fullName: System.ContextMarshalException.ContextMarshalException()
- uid: System.ContextMarshalException.#ctor(System.String)
  parent: System.ContextMarshalException
  isExternal: false
  name: ContextMarshalException(String)
  nameWithType: ContextMarshalException.ContextMarshalException(String)
  fullName: System.ContextMarshalException.ContextMarshalException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ContextMarshalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ContextMarshalException
  isExternal: false
  name: ContextMarshalException(SerializationInfo,StreamingContext)
  nameWithType: ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)
  fullName: System.ContextMarshalException.ContextMarshalException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ContextMarshalException.#ctor(System.String,System.Exception)
  parent: System.ContextMarshalException
  isExternal: false
  name: ContextMarshalException(String,Exception)
  nameWithType: ContextMarshalException.ContextMarshalException(String,Exception)
  fullName: System.ContextMarshalException.ContextMarshalException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.ContextMarshalException.#ctor*
  parent: System.ContextMarshalException
  isExternal: false
  name: ContextMarshalException
  nameWithType: ContextMarshalException.ContextMarshalException
